"""Add status to project_members

Revision ID: 60c6ac6468e6
Revises: 901af4f6dbcf
Create Date: 2026-04-05 20:35:00.813311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60c6ac6468e6'
down_revision: Union[str, None] = '901af4f6dbcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_members', sa.Column('status', sa.String(length=50), server_default='pending', nullable=False))
    op.add_column('project_members', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_members', 'created_at')
    op.drop_column('project_members', 'status')
    # ### end Alembic commands ###
