"""make time_entry task_id nullable

Revision ID: b224a4ef1d92
Revises: c6cd9b66da1f
Create Date: 2026-04-05 18:31:36.229063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b224a4ef1d92'
down_revision: Union[str, None] = 'c6cd9b66da1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('time_entries', 'task_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('time_entries', 'task_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
