"""Add is_superadmin

Revision ID: c6cd9b66da1f
Revises: 86907f04b4f7
Create Date: 2026-04-05 18:12:58.591934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6cd9b66da1f'
down_revision: Union[str, None] = '86907f04b4f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superadmin', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_superadmin')
    # ### end Alembic commands ###
